chart = c3.generate(
    bindto: '#chart'
    data:
        x: 'x'
        columns: [
            [
                'x'
                '2022-01-01'
                '2022-02-01'
                '2022-03-01'
                '2022-04-01'
                '2022-05-01'
                '2022-06-01'
                '2022-07-01'
                '2022-08-01'
                '2022-09-01'
                '2022-10-01'
                '2022-11-01'
                '2022-12-01'
            ]
            [
                'data1'
                1000
                1500
                1200
                2000
                1800
                2200
                2500
                2400
                2900
                2800
                3200
                3000
            ]
            [
                'data2'
                800
                1000
                900
                1200
                1100
                1400
                1500
                1400
                1700
                1600
                1900
                1800
            ]
            [
                'data3'
                400
                500
                600
                700
                800
                900
                1000
                1100
                1200
                1300
                1400
                1500
            ]
        ]
        types:
            data1: 'area'
            data2: 'area'
            data3: 'area'
        colors:
            data1: 'RGBA(0, 0, 128, 1)'
            data2: '#FFA500'
            data3: 'green'
        names:
            data1: 'Pigs'
            data2: 'Cats'
            data3: 'Dogs'
    axis:
        x:
            type: 'timeseries'
            tick: format: '%Y-%m'
        y:
            label:
                text: 'Sales'
                position: 'outer-middle'
            tick: format: d3.format(',')
    title:
        text: 'Monthly Sales in 2022'
        position: 'top-center')

# ---
# generated by js2coffee 2.2.0